version: "3"
services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    container_name: generate_pdf_container
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    links:
      - db

  db:
    container_name: banco
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - generate_pdf_data:/var/lib/postgresql/data
volumes:
  generate_pdf_data:
