default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>

development:
  <<: *default
  database: generate_pdf_development
test:
  <<: *default
  database: generate_pdf_test
production:
  <<: *default
  database: generate_pdf_production
  username: generate_pdf
  password: <%= ENV['GENERATE_PDF_DATABASE_PASSWORD'] %>
